Repository hawariMuflihMunte/Tugas.ku, pull requests merged in 2023-06, with the labels that each got.

#23 Update data structure and render
  src/scripts/global/config.js
  src/scripts/utils/FormTask.js
  src/scripts/utils/TaskList.js
  src/scripts/utils/card.js
  src/scripts/utils/circularProgress.js
  src/scripts/utils/convertDate.js
  src/scripts/utils/detail.js
  src/scripts/utils/drawer.js
  src/scripts/utils/generateId.js
  src/scripts/utils/loader.js
  src/scripts/utils/storageManagement.js
  src/scripts/views/app.js
  src/scripts/views/pages/dashboard.js
  src/scripts/views/pages/details.js
  src/stylesheet/nav.scss
  src/stylesheet/styles.scss
Labels: enhancement, help wanted, installment

#24 PWA
  package-lock.json
  package.json
  src/assets/app.webmanifest
  src/assets/icons/apple-icon-180.png
  src/assets/icons/manifest-icon-192.maskable.png
  src/assets/icons/manifest-icon-512.maskable.png
  src/assets/images/logo.png
  src/index.html
  src/scripts/global/config.js
  src/scripts/index.js
  src/scripts/utils/FormTask.js
  src/scripts/utils/TaskList.js
  src/scripts/utils/card.js
  src/scripts/utils/circularProgress.js
  src/scripts/utils/convertDate.js
  src/scripts/utils/detail.js
  src/scripts/utils/drawer.js
  src/scripts/utils/generateId.js
  src/scripts/utils/loader.js
  src/scripts/utils/storageManagement.js
  src/scripts/utils/sw-register.js
  src/scripts/views/app.js
  src/scripts/views/pages/dashboard.js
  src/scripts/views/pages/details.js
  src/stylesheet/nav.scss
  src/stylesheet/styles.scss
  webpack.dev.js
Labels: enhancement, help wanted, installment

#25 Testing + PWA
  codecept.conf.js
  jsconfig.json
  karma.conf.js
  package-lock.json
  package.json
  src/assets/app.webmanifest
  src/assets/icons/apple-icon-180.png
  src/assets/icons/manifest-icon-192.maskable.png
  src/assets/icons/manifest-icon-512.maskable.png
  src/assets/images/logo.png
  src/index.html
  src/scripts/global/config.js
  src/scripts/index.js
  src/scripts/utils/FormTask.js
  src/scripts/utils/TaskList.js
  src/scripts/utils/card.js
  src/scripts/utils/circularProgress.js
  src/scripts/utils/convertDate.js
  src/scripts/utils/detail.js
  src/scripts/utils/drawer.js
  src/scripts/utils/generateId.js
  src/scripts/utils/loader.js
  src/scripts/utils/storageManagement.js
  src/scripts/utils/sw-register.js
  src/scripts/views/app.js
  src/scripts/views/pages/dashboard.js
  src/scripts/views/pages/details.js
  src/stylesheet/nav.scss
  src/stylesheet/styles.scss
  steps.d.ts
  steps_file.js
  webpack.dev.js
Labels: enhancement, help wanted, question, design, installment, testing

#26 Enhancement of App's CRUD mode
  package-lock.json
  package.json
  src/scripts/classes/Backlog.js
  src/scripts/classes/Controller.js
  src/scripts/classes/Presenter.js
  src/scripts/classes/Utils.js
  src/scripts/routes/UrlParser.js
  src/scripts/utils/TaskList.js
  src/scripts/utils/card.js
  src/scripts/utils/circularProgress.js
  src/scripts/utils/convertDate.js
  src/scripts/utils/customMonthNames.js
  src/scripts/utils/detail.js
  src/scripts/utils/loader.js
  src/scripts/utils/storageManagement.js
  src/scripts/views/app.js
  src/scripts/views/pages/dashboard.js
  src/scripts/views/pages/details.js
  src/scripts/views/pages/splashScreen.js
  src/stylesheet/styles.scss
Labels: documentation, enhancement, help wanted, design, installment, testing

#27 CRUD Enhancement
  .gitignore
  LICENSE
  README.md
  e2e/Task.spec.js
  output/Showing_empty_task_in_dashboard.failed.png
  package-lock.json
  package.json
  src/scripts/classes/Backlog.js
  src/scripts/classes/Controller.js
  src/scripts/classes/Presenter.js
  src/scripts/classes/Utils.js
  src/scripts/classes/UtilsDrawer.js
  src/scripts/global/config.js
  src/scripts/routes/UrlParser.js
  src/scripts/utils/FormTask.js
  src/scripts/utils/TaskList.js
  src/scripts/utils/card.js
  src/scripts/utils/circularProgress.js
  src/scripts/utils/convertDate.js
  src/scripts/utils/customMonthNames.js
  src/scripts/utils/detail.js
  src/scripts/utils/loader.js
  src/scripts/utils/storageManagement.js
  src/scripts/views/app.js
  src/scripts/views/pages/dashboard.js
  src/scripts/views/pages/details.js
  src/scripts/views/pages/splashScreen.js
  src/stylesheet/styles.scss
Labels: enhancement, help wanted, design, installment, testing

#29 Merge Testing branch to Main branch
  .gitignore
  codecept.conf.js
  e2e/Opening_SplashScreen_Page.spec.js
  e2e/Task.spec.js
  e2e/Task_CRUD.spec.js
  output/Showing_empty_task_in_dashboard.failed.png
  src/scripts/classes/Presenter.js
  src/scripts/views/pages/splashScreen.js
Labels: bug, enhancement, help wanted, invalid

#30 Search task
  src/scripts/classes/Controller.js
  src/scripts/views/pages/dashboard.js
Labels: bug, enhancement, installment

#31 Bug fix patch
  src/scripts/classes/Controller.js
  src/scripts/classes/Presenter.js
  src/scripts/views/pages/dashboard.js
Labels: enhancement

#33 Add Dicoding mandatory meta tag
  src/index.html
Labels: documentation
